#!/bin/sh -eu

# Verify that all interfaces are connected

plugs="
  rosbag2-recorder-parameters
  rclone-parameters
"

for plug in ${plugs}; do
  while ! snapctl is-connected ${plug}; do
    # echo "Plug '${plug}' isn't connected, please run: snap connect ${SNAP_NAME}:${plug}"
    logger -t ${SNAP_NAME} "Plug '${plug}' isn't connected, \
      please run: snap connect ${SNAP_NAME}:${plug}"
    sleep 1
  done
done

# Verify that the necessary parameters are set

params="
  rob-cos-base-url
  device-uid
  rob-cos-s3-access-key-id
  rob-cos-s3-secret-access-key
"

for param in ${params}; do
  while [ -z "$(snapctl get ${param})" ]; do
    # echo "Waiting for parameter '${param}' to be set..."
    logger -t ${SNAP_NAME} "Waiting for parameter '${param}' to be set..."
    sleep 1
  done
done

# Update the configuration files with the current parameter values

cp -R ${SNAP}/etc/configuration/ ${SNAP_COMMON}/
. ${SNAP}/usr/bin/search_and_replace

rosbag2_config="${SNAP_COMMON}/configuration/ros2-exporter-agent/rosbag2-recorder.yaml"
if [ ! -f "${rosbag2_config}" ]; then
  logger -t ${SNAP_NAME} "Configuration file not found: ${rosbag2_config}"
  exit 1
fi

rclone_config="${SNAP_COMMON}/configuration/ros2-exporter-agent/rclone.conf"
if [ ! -f "${rclone_config}" ]; then
  logger -t ${SNAP_NAME} "Configuration file not found: ${rclone_config}"
  exit 1
fi

snapctl set-health okay

# Dispatch the configuration values to the respective plugs

# The confdb custodian may not be immediately available,
# so we implement a retry mechanism
snapctl_set_view_retry() {
  while true; do
    output="$(snapctl set --view "$@" 2>&1)" && return 0
    if echo "${output}" | grep -q "no custodian"; then
      # echo "No custodian yet, retrying: snapctl $*"
      logger -t ${SNAP_NAME} "No custodian yet, retrying: snapctl set --view $1 ..."
      sleep 1
    else
      echo "${output}" >&2
      return 1
    fi
  done
}

snapctl_set_view_retry :rosbag2-recorder-parameters file="$(cat ${rosbag2_config})"
snapctl_set_view_retry :rclone-parameters file="$(cat ${rclone_config})"
snapctl_set_view_retry :rclone-parameters bucket="$(snapctl get rob-cos-s3-bucket)"

snapctl stop --disable ${SNAP_NAME}.dispatch-confdb || true
