[fileserver]
type = sftp
host = rob-cos-ip-placeholder
user = root
port = 2222
key_file = /root/snap/ros2-exporter-agent/common/device_rsa_key
[bagstore]
type = alias
remote = fileserver:/var/lib/caddy-fileserver/robot-uid-placeholder
