[s3microceph]
type = s3
provider = Ceph
env_auth = false
access_key_id = rob-cos-access-key-id-placeholder
secret_access_key = rob-cos-secret-access-key-placeholder
endpoint = http://rob-cos-ip-placeholder
force_path_style = true
[bagstore]
type = alias
remote = s3microceph:robot-uid-placeholder
