name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  main:
    uses: canonical/ros-cos-demo-configuration/.github/workflows/snap.yaml@main
    with:
      branch-name: "main"

