name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  basic:
    uses: canonical/rob-cos-demo-configuration/.github/workflows/snap.yaml@basic
    permissions:
      contents: read
      actions: write
    with:
      branch-name: "basic"
  advanced:
    uses: canonical/rob-cos-demo-configuration/.github/workflows/snap.yaml@advanced
    permissions:
      contents: read
      actions: write
    with:
      branch-name: "advanced"
