name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  basic:
    uses: canonical/rob-cos-demo-configuration/.github/workflows/snap.yaml@main
    with:
      branch: "basic"
  advanced:
    uses: canonical/rob-cos-demo-configuration/.github/workflows/snap.yaml@main
    with:
      branch: "advanced"
