name: snap
on:
  push:
    branches:
      - basic
  pull_request:
    branches:
      - basic
  workflow_dispatch:
  workflow_call:
   inputs:
      branch:
        required: false
        type: string
        default: ''

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snap-track: basic
      snap-risk: beta
