#!/bin/sh -e

# The connect hook cannot access confdb (it would cause a deadlock).
# Start the init-confdb service to handle initialization.
# It's installed as disabled, so we need to start it explicitly.

logger "cos-registration-agent-control-configuration interface connected, starting init-confdb service"
snapctl start --enable rob-cos-demo-configuration.init-confdb

exit 0

