#!/bin/sh -e

# Copy configuration files to SNAP_COMMON (including defaults/ folder)
cp -R $SNAP/etc/configuration/ $SNAP_COMMON/

# Note: Device UID and other configuration now initialized via confdb
# in connect-plug-device-cos-settings-control hook
